### ISSUE TITLE
Readme: Add instructions

### ISSUE THREAD

**Issue by vin-ni** [aiberlin/NTMI#25]
Copy Github folder into SuperCollider > downloaded-quarks. Then run `Quarks.install("NTMI")`

**Comment by vin-ni** [comment]
At least i couldnt install it directly via git

**Comment by vin-ni** [comment]
I needed to use ´Quarks.install("https://github.com/aiberlin/NTMI")´

**Comment by adcxyz** [comment]
Yes, correct, this installs the dependencies.
