### ISSUE TITLE
Excluding one of the 'defaultActives' sounds from the POOL introduces problems in the UI

### ISSUE THREAD

**Issue by fracnesco** [aiberlin/NTMI#29]
If one of the 4 sounds which is by default loaded at start up is exlcuded from the sound  POOL, this creates weird behaviour in the UI.
You can change the sounds that load at start up by chainging the  'defaultActives'  in ntmi_prefs_default.scd

Tested on Windows

**Comment by adcxyz** [comment]
thanks francesco, will look into it

**Comment by adcxyz** [comment]
fixed with [5aea6d9]
